CREATE TABLE IF NOT EXISTS daily_reports (
    id_report integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal date NULL,
    rata_kelembapan double precision NULL,
    intensitas_cahaya double precision NULL,
    rata_suhu double precision NULL,
    total_penyiraman integer NULL
);

CREATE TABLE IF NOT EXISTS devices (
    id_device integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_device varchar(100) NULL,
    lokasi_lahan varchar(150) NULL,
    status varchar(8) NULL CHECK (status IN ('aktif', 'nonaktif'))
);

CREATE TABLE IF NOT EXISTS users (
    id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    nama varchar(100) NOT NULL,
    role varchar(5) NOT NULL CHECK (role IN ('admin', 'user')),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS login_logs (
    id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user integer NULL REFERENCES users (id_user),
    waktu_login timestamp without time zone NULL,
    status_login varchar(8) NULL CHECK (status_login IN ('berhasil', 'gagal')),
    ip_address varchar(45) NULL
);

CREATE TABLE IF NOT EXISTS schedules (
    id_schedule integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    waktu_mulai time without time zone NULL,
    durasi integer NULL,
    status varchar(8) NULL CHECK (status IN ('aktif', 'nonaktif'))
);

CREATE TABLE IF NOT EXISTS sensors (
    id_sensor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_device integer NULL REFERENCES devices (id_device),
    jenis_sensor varchar(10) NULL CHECK (jenis_sensor IN ('kelembapan', 'suhu')),
    satuan varchar(10) NULL
);

CREATE TABLE IF NOT EXISTS sprinkler_logs (
    id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(3) NULL CHECK (status IN ('ON', 'OFF')),
    waktu timestamp without time zone NULL,
    sumber varchar(8) NULL CHECK (sumber IN ('manual', 'otomatis'))
);

CREATE TABLE IF NOT EXISTS telemetry_logs (
    id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sensor integer NULL REFERENCES sensors (id_sensor),
    nilai_sensor double precision NULL,
    timestamp timestamp without time zone NULL
);

CREATE TABLE IF NOT EXISTS thresholds (
    id_threshold integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batas_kelembapan double precision NULL,
    batas_suhu double precision NULL,
    updated_by integer NULL REFERENCES users (id_user)
);

CREATE TABLE IF NOT EXISTS uploads (
    id_upload integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_file varchar(255) NULL,
    tanggal_upload timestamp without time zone NULL,
    uploaded_by integer NULL REFERENCES users (id_user)
);

INSERT INTO devices (id_device, nama_device, lokasi_lahan, status)
VALUES (1, 'Node Uji', 'Sawah', 'aktif')
ON CONFLICT (id_device) DO NOTHING;

INSERT INTO sensors (id_sensor, id_device, jenis_sensor, satuan)
VALUES (1, 1, 'kelembapan', '%')
ON CONFLICT (id_sensor) DO NOTHING;

INSERT INTO telemetry_logs (id_log, id_sensor, nilai_sensor, timestamp)
VALUES (2, 1, 45, '2026-04-20 00:18:56')
ON CONFLICT (id_log) DO NOTHING;

INSERT INTO users (id_user, username, password, nama, role, created_at)
VALUES (20220201, 'lianazein', '12345678', 'liana_zein', 'admin', '2026-04-23 13:59:22')
ON CONFLICT (id_user) DO NOTHING;

SELECT setval(pg_get_serial_sequence('devices', 'id_device'), GREATEST(COALESCE((SELECT MAX(id_device) FROM devices), 1), 1), true);
SELECT setval(pg_get_serial_sequence('sensors', 'id_sensor'), GREATEST(COALESCE((SELECT MAX(id_sensor) FROM sensors), 1), 1), true);
SELECT setval(pg_get_serial_sequence('telemetry_logs', 'id_log'), GREATEST(COALESCE((SELECT MAX(id_log) FROM telemetry_logs), 1), 1), true);
SELECT setval(pg_get_serial_sequence('users', 'id_user'), GREATEST(COALESCE((SELECT MAX(id_user) FROM users), 1), 1), true);
