# Generated by Django 6.0.4 on 2026-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('rata_kelembapan', models.FloatField(blank=True, null=True)),
                ('intensitas_cahaya', models.FloatField(blank=True, null=True)),
                ('rata_suhu', models.FloatField(blank=True, null=True)),
                ('total_penyiraman', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id_device', models.AutoField(primary_key=True, serialize=False)),
                ('nama_device', models.CharField(blank=True, max_length=100, null=True)),
                ('lokasi_lahan', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('aktif', 'aktif'), ('nonaktif', 'nonaktif')], max_length=8, null=True)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_login', models.DateTimeField(blank=True, null=True)),
                ('status_login', models.CharField(blank=True, choices=[('berhasil', 'berhasil'), ('gagal', 'gagal')], max_length=8, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'login_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_mulai', models.TimeField(blank=True, null=True)),
                ('durasi', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('aktif', 'aktif'), ('nonaktif', 'nonaktif')], max_length=8, null=True)),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_sensor', models.CharField(blank=True, choices=[('kelembapan', 'kelembapan'), ('suhu', 'suhu')], max_length=10, null=True)),
                ('satuan', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sensors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SprinklerLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=3, null=True)),
                ('waktu', models.DateTimeField(blank=True, null=True)),
                ('sumber', models.CharField(blank=True, choices=[('manual', 'manual'), ('otomatis', 'otomatis')], max_length=8, null=True)),
            ],
            options={
                'db_table': 'sprinkler_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_sensor', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telemetry_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id_threshold', models.AutoField(primary_key=True, serialize=False)),
                ('batas_kelembapan', models.FloatField(blank=True, null=True)),
                ('batas_suhu', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thresholds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id_upload', models.AutoField(primary_key=True, serialize=False)),
                ('nama_file', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_upload', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
